// src/gatsby-plugin-theme-ui/index.js
import { base } from '@theme-ui/presets'

const theme = {
  ...base,
  config: {
    useColorSchemeMediaQuery: 'system', // Automatically respects system preferences
  },
  colors: {
    ...base.colors,
    primary: 'black',
    primaryMuted: '#eeeeeeff',
    textMuted: '#777777ff',
    secondary: '#30c',
    badgeSecondaryBg: 'black',
    badgeSecondaryText: 'white',
    badgeSecondaryBorder: 'black',
    primaryText: 'white',
    cardBorderColor: '#e1e1e1',
    cardBackgroundColor: '#f8f8f8',
    showCardBackground: '#f5f5f5',
    highlightedItem: 'yellow',
    text: '#212121ff',

    modes: {
      dark: {
        primaryMuted: '#525252ff',
        text: 'white',
        background: 'black',
        badgeSecondaryBg: 'black',
        badgeSecondaryText: 'white',
        badgeSecondaryBorder: 'white',
        primary: 'white',
        primaryText: 'black',
        cardBorderColor: '#464646',
        cardBackgroundColor: 'black',
        showCardBackground: '#3b3b3b',
      },
    },
  },
  fonts: {
    body: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif',
    headline:
      'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif',
    serif:
      'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif',
    mono: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif',
  },
  fontSizes: [12, 14, 16, 20, 24, 32, 48, 64, 72],
  fontWeights: {
    body: 400,
    heading: 700,
    bold: 700,
  },
  lineHeights: {
    body: 1.5,
    heading: 1.25,
  },
  styles: {
    root: {
      fontFamily: 'body',
      fontWeight: 'body',
    },
    h1: {
      fontFamily: 'body',
      fontWeight: 'heading',
      lineHeight: 'heading',
      fontSize: 5,
    },
    h2: {
      fontFamily: 'body',
      fontWeight: 'headline',
      borderLeftWidth: [0, 0, '1px'],
      paddingTop: [3],
      paddingBottom: [0],
    },
    ol: {
      // listStylePosition: 'inside',
      listStylePosition: 'outside',
      fontSize: 18,
    },
    ul: {
      paddingLeft: [2, 2, 3],

      listStyle: 'disc',
      listStylePosition: 'outside',
      fontSize: 18,
      'li::marker': {
        color: 'textMuted',
      },
    },
    blockquote: {
      backgroundColor: 'blockquoteBg',
      paddingX: '20px',
      paddingY: '20px',
      margin: '0',
      color: 'text',
      borderLeftWidth: '3px',
      borderLeftStyle: 'solid',
      borderLeftColor: 'textMuted',
    },
    hr: {
      color: 'primaryMuted',
    },
    p: {
      fontFamily: 'body',
      lineHeight: '30px',
      fontSize: 18,
      fontWeight: '400',
      color: 'text',
    },
    a: {
      ':hover, :focus': {
        color: 'text',
      },
      textDecoration: 'none',
      color: 'text',
    },
    li: {
      fontFamily: 'body',
      fontSize: 18,
      marginBottom: '20px',
      paddingLeft: 2, // or adjust as needed
    },
    faded: {
      position: 'fixed',
      top: '0',
      height: '100%',
      width: '100%',
      left: '0',
      backgroundColor: 'rgba(0,0,0,0.8)',
      zIndex: 10000,
      display: 'flex',
    },
  },
  badges: {
    primary: {
      bg: 'white',
      color: 'black',
      borderRadius: '15px',
      px: 2,
      py: 1,
      fontSize: 1,
      fontWeight: 'bold',
      border: '1px solid black',
    },
    listSection: {
      fontFamily: 'headline',
      padding: '5px',
      fontSize: ['0', '1', '1'],
      color: 'background',
      textTransform: 'uppercase',
      marginRight: '5px',
    },
    em: { fontWeight: '500' },
    secondary: {
      bg: 'secondary',
      color: 'background',
      borderRadius: '4px',
      px: 2,
      py: 1,
      fontSize: 1,
      fontWeight: 'bold',
    },
    outline: {
      bg: 'transparent',
      color: 'primary',
      border: '1px solid',
      borderColor: 'primary',
      borderRadius: '4px',
      px: 2,
      py: 1,
      fontSize: 1,
    },
  },
  variants: {
    linkCard: {
      display: 'flex',
      textDecoration: 'none',
      alignItems: 'center',
      p: 3,
      mb: 3,
      border: '2px solid',
      borderColor: 'primary',
      borderRadius: 0,
      transition: 'box-shadow 0.2s ease',
      '&:hover': {
        boxShadow: 'card',
      },
    },
  },
  boxes: {
    figure: {
      maxWidth: [null, null, '690px'],
      backgroundColor: 'primaryMuted',
      padding: '30px',
      borderRadius: '5px',
      marginLeft: 'auto',
      marginRight: 'auto',
      marginTop: '60px',
      marginBottom: '60px',
    },
  },
  images: {
    postCardImage: {
      width: ['100%', '200px', '300px'],
      height: ['300px', '150px', '200px'],
      zIndex: '0',
    },
    homePageImage: {
      width: ['100%', '200px', '200px'],
      height: '200px',
      zIndex: '0',
    },
    relatedImage: {
      width: ['100%', '200px', '300px'],
      height: ['300px', '150px', '200px'],
      zIndex: '0',
    },
    fullScreen: {
      position: 'relative',
      height: '100vh',
      maxHeight: '100%',
      zIndex: '100',
      borderRadius: [4, 4, 4],
    },
  },
  text: {
    headline: {
      fontFamily: 'headline',
      fontSize: '6',
      fontWeight: 'heavy',
      // lineHeight: "0",
      letterSpacing: '0',
      color: 'text',
    },
    heading3: {
      fontFamily: 'serif',
      fontSize: '4',
      fontWeight: '600',
      // lineHeight: "0",
      textDecoration: 'none',
      letterSpacing: '0',
      color: 'text',
    },
    postCardType: {
      fontSize: '16px',
      fontFamily: 'body',
      textTransform: 'uppercase',
      fontWeight: '600',
      // letterSpacing: '1px',
      color: 'mutedText',
      display: 'block',
    },
    postCardTitle: {
      fontSize: ['2', '3', '3'],
      fontFamily: 'serif',
      fontWeight: '600',
      color: 'text',
    },
    postCardSubtitle: {
      fontSize: ['14px', '2', '16px'],
      fontFamily: 'body',
      fontWeight: 400,
      color: 'mutedText',
      letterSpacing: '0.3px',
    },
    postCardBottom: {
      fontSize: ['14px', '2', '16px'],
      fontFamily: 'body',
      fontWeight: 400,
      color: 'mutedText',
      letterSpacing: '0.3px',
      height: '100%',
    },
    resultsHeading: {
      // lineHeight: '30px',
      fontFamily: 'body',
      // letterSpacing: '.6px',
      fontWeight: '700',
    },
    resultsItem: {
      fontSize: [16, 16, 17],
      // lineHeight: "35px",
      fontFamily: 'body',
    },
    highlightedItem: {
      textDecorationLine: 'underline',
      textDecorationThickness: '10px',
      textUnderlineOffset: '-8px',
      textDecorationSkipInk: 'none',
      textDecorationColor: 'highlightedItem',
      fontSize: [16, 16, 17],
      // lineHeight: "35px",
      fontFamily: 'body',
    },
    caption: {
      marginTop: '5px',
      display: 'block',
      color: 'primary',
      fontFamily: 'body',
      fontStyle: 'normal',
      fontSize: '13px',
    },
    postSubtitle: {
      fontFamily: 'body',
      fontWeight: '400',
      letterSpacing: '0px',
      fontSize: ['14px', '16px', '16px'],
    },
    postTitle: {
      fontFamily: 'body',
      fontWeight: 600,
      fontStyle: 'normal',
      fontSize: ['24px', '32px', '32px'],
      color: 'textInvert',
    },
    postType: {
      fontFamily: 'body',
      fontWeight: '700',
      letterSpacing: '.1em',
      fontSize: ['12px', '16px', '16px'],
      textTransform: 'uppercase',
      color: 'primary',
      lineHeight: '130%',
    },
    raceStatHeading: {
      fontFamily: 'body',
      // color: 'primary',
      fontWeight: '300',
      // letterSpacing: '1px',
      // textTransform: 'uppercase',
      fontSize: [1],
    },
  },

  links: {
    menu: {
      fontSize: ['22px', '22px', '22px'],
      // textTransform: 'uppercase',
      fontWeight: '700',
      lineHeight: '1.5',
      margin: '0',
      fontFamily: 'body',
      color: 'text',
      '&:active': {
        color: 'activeMenuLink',
      },
    },
  },
}

export default theme
