import { Theme } from 'theme-ui'
import { darken, lighten } from '@theme-ui/color'

// example theme file
// @refresh reset
const colors = {
  cultured: '#f8f9faff',
  cultured2: '#e9ecefff',
  gainsboro: '#dee2e6ff',
  lightGray: '#ced4daff',
  cadetBlueCrayola: '#adb5bdff',
  sonicSilver: '#6c757dff',
  davysGrey: '#495057ff',
  onyx: '#343a40ff',
  eerieBlack: '#212529ff',
}

const theme: Theme = {
  config: {
    initialColorModeName: 'light',
  },
  styles: {
    // the keys used here reference elements in MDX
    h1: {
      // the style object for each element
      // can reference other values in the theme
      fontFamily: 'body',
      fontWeight: 100,
      lineHeight: 'headline',
      fontSize: ['3', '4', '5'],
      marginTop: 0,
      marginBottom: 3,
      letterSpacing: '-0.4px',
    },
    em: { fontWeight: '500' },
    h2: {
      fontFamily: 'body',
      fontWeight: 'headline',
      // lineHeight: 'headline',
      marginTop: 0,
      marginBottom: 3,
    },
    blockquote: {
      backgroundColor: 'blockquoteBg',
      paddingX: '20px',
      paddingY: '20px',
      margin: '0',
      color: 'text',
    },
    hr: {
      color: 'backgroundEmDark',
    },
    p: {
      fontFamily: 'serif',
      lineHeight: '1.6',
      fontSize: [16, 16, 17],
      fontFeatureSettings: "kern",
      fontKerning: 'normal',
      fontWeight: '400',
    },
    a: {
      ':hover, :focus': {
        color: 'secondary',
      },
      textDecoration: 'underline',
      color: 'text',
    },
    li: {
      fontFamily: 'serif',
      lineHeight: '1.5',
      letterSpacing: '.4px',
      fontSize: [16, 16, 17],
      paddingLeft: '10px',
      marginBottom: '10px',
    },
    ol: {
      paddingInlineStart: '20px',
    },
    faded: {
      position: 'fixed',
      top: '0',
      height: '100%',
      width: '100%',
      left: '0',
      backgroundColor: 'rgba(0,0,0,0.8)',
      zIndex: 10000,
      display: 'flex',
    },
    // more styles can be added as needed
  },
  buttons: {
    primary: {
      color: 'background',
      marginRight: 0,
      paddingX: '10px',
      paddingY: '5px',
      fontFamily: 'body',
      cursor: 'pointer',
      // textTransform: 'uppercase',
      fontWeight: '600',
      fontSize: '14px',
      letterSpacing: '.5px',
      paddingLeft: '20px',
      paddingRight: '20px',
    },
  },
  fontSizes: [10, 13, 18, 21, 26, 34, 48],
  fonts: {
    body: '"Public Sans Variable", sans-serif',
    headline: '"Public Sans Variable", sans-serif',
    serif: '"Public Sans Variable", sans-serif',
    mono: '"Public Sans Variable", sans-serif',
  },
  // sizes: {
  //   container: 768,
  // },
  cards: {
    primary: {
      padding: 0,
      borderRadius: 4,
      boxShadow: '0 8px 16px -4px rgba(0,0,0,.1), 0 0 8px -3px rgba(0,0,0,.1)',
      marginBottom: '20px',
      backgroundColor: 'cardBackground',
    },
  },
  images: {
    postCardImage: {
      width: ['100%', '200px', '300px'],
      height: ['300px', '150px', '200px'],
      zIndex: '0',
      borderTopLeftRadius: 4,
      borderTopRightRadius: [4, 0, 0],
      borderBottomLeftRadius: [0, 4, 4],
    },
    homePageImage: {
      width: ['600px', '600px', '600px'],
      height: ['300px', '400px', '400px'],
      zIndex: '0',
      borderTopLeftRadius: 4,
      borderTopRightRadius: [4, 0, 0],
      borderBottomLeftRadius: [0, 4, 4],
    },
    relatedImage: {
      width: ['100%', '200px', '300px'],
      height: ['300px', '150px', '200px'],
      zIndex: '0',
      borderTopLeftRadius: 4,
      borderTopRightRadius: [4, 0, 0],
      borderBottomLeftRadius: [0, 4, 4],
    },
    fullScreen: {
      position: 'relative',
      height: '100vh',
      maxHeight: '100%',
      zIndex: '100',
      borderRadius: [4, 4, 4],
    },
  },
  text: {
    headline: {
      fontFamily: 'headline',
      fontSize: '6',
      fontWeight: 'heavy',
      // lineHeight: "0",
      letterSpacing: '0',
      color: 'text',
    },
    heading3: {
      fontFamily: 'serif',
      fontSize: '4',
      fontWeight: '600',
      // lineHeight: "0",
      textDecoration: 'none',
      letterSpacing: '0',
      color: 'text',
    },
    postCardType: {
      fontSize: '16px',
      fontFamily: 'body',
      textTransform: 'uppercase',
      fontWeight: '600',
      // letterSpacing: '1px',
      color: 'mutedText',
      display: 'block',
    },
    postCardTitle: {
      fontSize: ['2', '3', '3'],
      fontFamily: 'serif',
      fontWeight: '600',
      color: 'text',
    },
    postCardSubtitle: {
      fontSize: ['14px', '2', '16px'],
      fontFamily: 'body',
      fontWeight: 400,
      color: 'mutedText',
      letterSpacing: '0.3px',
    },
    postCardBottom: {
      fontSize: ['14px', '2', '16px'],
      fontFamily: 'body',
      fontWeight: 400,
      color: 'mutedText',
      letterSpacing: '0.3px',
      height: '100%',
    },
    resultsHeading: {
      // lineHeight: '30px',
      fontFamily: 'body',
      // letterSpacing: '.6px',
      fontWeight: '700',
    },
    resultsItem: {
      fontSize: [16, 16, 17],
      // lineHeight: "35px",
      fontFamily: 'body',
    },
    highlightedItem: {
      textDecorationLine: 'underline',
      textDecorationThickness: '10px',
      textUnderlineOffset: '-8px',
      textDecorationSkipInk: 'none',
      textDecorationColor: 'highlightColor',
      fontSize: [16, 16, 17],
      // lineHeight: "35px",
      fontFamily: 'body',
    },
    caption: {
      marginTop: '5px',
      display: 'block',
      color: 'primary',
      fontFamily: 'body',
      fontStyle: 'normal',
      fontSize: '13px',
      // letterSpacing: '.1px',
    },
    postSubtitle: {
      marginX: 'auto',
      fontFamily: 'body',
      fontWeight: '400',
      letterSpacing: '0px',
      fontSize: ['14px', '16px', '16px'],
      // textTransform: 'uppercase',
      color: '#343a40',
      marginTop:['0px','5px','10px'],
      marginBottom: '40px',
    },
    postTitle: {
      fontFamily: 'serif',
      fontWeight: 700,
      fontStyle: 'normal',
      fontSize: ['20px', '5', '40px'],
      marginBottom: ['5px', '5px', '5px'],
      // letterSpacing: ['.6px', '1px', '1px'],
      marginX: 'auto',
      textAlign: 'center',
    },
    postType: {
      marginX: 'auto',
      fontFamily: 'body',
      fontWeight: '500',
      letterSpacing: '0px',
      fontSize: '16px',
      textTransform: 'uppercase',
      color: '#9fa8ae',
    },
    raceStatHeading: {
      fontFamily: 'body',
      // color: 'primary',
      fontWeight: '300',
      // letterSpacing: '1px',
      // textTransform: 'uppercase',
      fontSize: [1],
    },
  },
  badges: {
    listSection: {
      fontFamily: 'headline',
      padding: '5px',
      fontSize: ['0', '1', '1'],
      color: 'background',
      textTransform: 'uppercase',
      marginRight: '5px',
    },
  },
  links: {
    menu: {
      // fontSize: '24px',
      fontSize: ['22px', '22px', '22px'],
      textTransform: 'uppercase',
      fontWeight: '700',
      lineHeight: '1.5',
      margin: '0',
      fontFamily: 'body',
      color: 'headerForeground',
      '&:active': {
        color: 'activeMenuLink',
      },
    },
  },
  colors: {
    text: '#212529ff',
    muted: '#f8f9faff',
    mutedText: '#495057ff',
    background: '#fff',
    backgroundEm: darken('background', 0.06),
    backgroundEmDark: darken('background', 0.1),
    graphGrid: '#e9ecefff',
    graphFill: '#495057ff',
    primary: colors.sonicSilver,
    marker: darken('background', 0.4),
    headerColor: '#f8f9faff',
    graph: ['red', 'blue'],
    // headerForeground: "rgb(255, 116, 139)",
    headerForeground: colors.onyx,
    menuBackground: darken('background', 0.1),
    cardBackground: colors.cultured,
    blockquoteBg: '#e9ecefff',
    activeMenuLink: colors.cadetBlueCrayola,
    dividerColor: colors.gainsboro,
    highlightColor: '#e8ff50c7',
    opacity: '0.3',
    modes: {
      dark: {
        graphGrid: '#343a40ff',
        headerColor: colors.eerieBlack,
        dividerColor: colors.sonicSilver,
        text: colors.cultured,
        mutedText: '#6c757dff',
        graphFill: colors.cultured,
        background: colors.eerieBlack,
        backgroundEm: lighten('background', 0.06),
        backgroundEmDark: lighten('background', 0.1),
        muted: colors.eerieBlack,
        cardBackground: colors.onyx,
        primary: colors.gainsboro,
        marker: colors.cultured,
        menuBackground: lighten('background', 0.03),
        blockquoteBg: colors.davysGrey,
        headerForeground: '#ced4daff',
        highlightColor: '#6c757dff',
        opacity: '0.1',
      },
    },
  },
}

export default theme
